from typing import Annotated, Any, Literal
from typing_extensions import TypedDict

from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


# ============================================================
# Agent Types
# ============================================================

AgentName = Literal[
    "orchestrator",
    "computer",
    "coding",
    "browser",
    "research",
    "news",
    "vision",
    "memory",
    "system",
]


# ============================================================
# Execution Status
# ============================================================

ExecutionStatus = Literal[
    "idle",
    "understanding",
    "planning",
    "waiting_approval",
    "executing",
    "observing",
    "verifying",
    "replanning",
    "completed",
    "failed",
]


# ============================================================
# Main METHU State
# ============================================================

class MethuState(TypedDict, total=False):

    # --------------------------------------------------------
    # Conversation
    # --------------------------------------------------------

    messages: Annotated[list[BaseMessage], add_messages]

    user_input: str
    final_response: str

    # --------------------------------------------------------
    # Understanding
    # --------------------------------------------------------

    intent: str
    language: str

    # --------------------------------------------------------
    # Planning
    # --------------------------------------------------------

    # Temporary plan generated by the orchestrator.
    # This will eventually be replaced by structured_plan.
    plan: list[str]

    # Structured execution plan generated by planner.py.
    structured_plan: list[dict[str, Any]]

    # Current numerical step.
    current_step: int

    # Full current plan step.
    current_plan_step: dict[str, Any] | None

    # Results from completed execution steps.
    execution_results: list[dict[str, Any]]

    # --------------------------------------------------------
    # Agent Routing
    # --------------------------------------------------------

    selected_agent: AgentName

    # --------------------------------------------------------
    # Tool Execution
    # --------------------------------------------------------

    tool_name: str | None

    tool_input: dict[str, Any]

    tool_result: Any

    # --------------------------------------------------------
    # Execution State
    # --------------------------------------------------------

    status: ExecutionStatus

    error: str | None

    # Number of retries attempted for the current plan step.
    retry_count: int

    # Maximum retries allowed for one step before replanning.
    max_retries: int

    # Reason why the most recent execution or verification failed.
    retry_reason: str | None

    # Number of times METHU has replanned the current task.
    replan_count: int

    # Maximum number of replans allowed before METHU stops safely.
    max_replans: int

# --------------------------------------------------------
# Verification
# --------------------------------------------------------


verified: bool

verification_message: str

# --------------------------------------------------------
# Permission / Security
# --------------------------------------------------------

requires_approval: bool

approval_granted: bool | None

risk_level: Literal[
    "low",
    "medium",
    "high",
]

# --------------------------------------------------------
# Memory
# --------------------------------------------------------

memory_context: list[str]

# --------------------------------------------------------
# Vision
# --------------------------------------------------------

image_paths: list[str]

screenshot_path: str | None

# --------------------------------------------------------
# UI
# --------------------------------------------------------

ui_event: str | None

ui_payload: dict[str, Any]

# --------------------------------------------------------
# Session
# --------------------------------------------------------

session_id: str
